# -*- coding: utf-8 -*-
"""01_explore_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkR4W2G9_0C569-alUw9oKRrcTo0LYjo

# Mount google drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Import librari load dataset and check the dataset"""

import pandas as pd

# Step 1: Load the CSV from Google Drive instead of your laptop
df = pd.read_csv("/content/drive/MyDrive/smart-support-assistant/dataset-tickets-multi-lang-4-20k.csv")

# Step 2: Print how many rows and columns
print("Shape (rows, columns):", df.shape)

# Step 3: Print column names
print("\nColumn names:", list(df.columns))

# Step 4: Peek at the first 5 rows
df.head()

df.info()

# --- 1. Missing values ---
print("Missing values per column:")
print(df.isnull().sum())

# --- 2. Duplicate rows ---
print("\nNumber of exact duplicate rows:", df.duplicated().sum())

# --- 3. Language distribution ---
print("\nLanguage counts:")
print(df['language'].value_counts())

# --- 4. Target column distribution (class balance) ---
print("\n'queue' column distribution:")
print(df['queue'].value_counts())

print("\n'type' column distribution:")
print(df['type'].value_counts())

# --- 5. Text length check (too-short tickets) ---
df['body_length'] = df['body'].astype(str).apply(len)
print("\nShortest 5 ticket bodies (by character count):")
print(df.nsmallest(5, 'body_length')[['body', 'body_length']])

# --- 6. Peek for HTML/junk characters ---
print("\nSample of 3 raw ticket bodies (look for <tags> or &amp; etc.):")
for text in df['body'].dropna().sample(3, random_state=1):
    print("---")
    print(text[:300])  # first 300 characters only

"""# Clean the dataset"""

import re

# --- 1. Keep only English rows ---
df_clean = df[df['language'] == 'en'].copy()
print("After English filter:", df_clean.shape)

# --- 2. Drop the sparse tag columns ---
df_clean = df_clean.drop(columns=['tag_5', 'tag_6', 'tag_7', 'tag_8'])

# --- 3. Drop rows with a truly missing body ---
df_clean = df_clean.dropna(subset=['body'])
print("After dropping missing bodies:", df_clean.shape)

# --- 4. Fill missing subject with empty text instead of dropping ---
df_clean['subject'] = df_clean['subject'].fillna('')

# --- 5. A text-cleaning function we'll reuse everywhere ---
def clean_text(text):
    text = str(text)
    text = re.sub(r'<.*?>', ' ', text)      # remove HTML tags like <br>
    text = re.sub(r'&\w+;', ' ', text)      # remove HTML entities like &amp;
    text = re.sub(r'\s+', ' ', text)        # collapse multiple spaces/newlines into one
    text = text.strip().lower()             # remove leading/trailing spaces, lowercase everything
    return text

df_clean['body_clean'] = df_clean['body'].apply(clean_text)
df_clean['subject_clean'] = df_clean['subject'].apply(clean_text)

# --- 6. NOW drop rows where the CLEANED body is too short ---
df_clean = df_clean[df_clean['body_clean'].str.len() >= 15]
print("After dropping too-short bodies:", df_clean.shape)

# --- 7. Save the cleaned dataset ---
output_path = "/content/drive/MyDrive/smart-support-assistant/tickets_clean.csv"
df_clean.to_csv(output_path, index=False)
print("\nSaved cleaned file to:", output_path)
print("Final shape:", df_clean.shape)

"""#Splitting data into "practice" and "test" sets"""

from sklearn.model_selection import train_test_split

# Our input (X) is the cleaned ticket text, our target (y) is the category we want to predict
X = df_clean['body_clean']
y = df_clean['type']

# Split: 80% for training (learning), 20% for testing (checking)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])

"""# Turning text into numbers a model can understand (TF-IDF)"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Create the TF-IDF converter
vectorizer = TfidfVectorizer(
    max_features=5000,   # only keep the 5000 most useful words (keeps things fast)
    stop_words='english'  # automatically ignore common words like "the", "is", "and"
)

# Learn the vocabulary from TRAINING data only, and convert it to numbers
X_train_tfidf = vectorizer.fit_transform(X_train)

# Convert TEST data using the SAME vocabulary (don't re-learn on test data!)
X_test_tfidf = vectorizer.transform(X_test)

print("Training data shape (tickets, words):", X_train_tfidf.shape)

"""# Training the actual model"""

from sklearn.linear_model import LogisticRegression

# Create the model
model = LogisticRegression(max_iter=1000, random_state=42)

# Train it - this is where the "learning" actually happens
model.fit(X_train_tfidf, y_train)

print("Model trained!")

"""# Testing how well it learned"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Make predictions on the test set (data it's never seen)
y_pred = model.predict(X_test_tfidf)

# How many did it get right overall?
print("Accuracy:", accuracy_score(y_test, y_pred))

# Detailed breakdown per category
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

fig, ax = plt.subplots(figsize=(7, 6))
ConfusionMatrixDisplay.from_predictions(
    y_test, y_pred, xticks_rotation=45, ax=ax, cmap='Blues'
)
plt.title("Confusion Matrix: What gets mistaken for what")
plt.tight_layout()
plt.show()

"""# Saving this baseline model, so we don't lose it"""

import joblib

joblib.dump(model, "/content/drive/MyDrive/smart-support-assistant/baseline_model.pkl")
joblib.dump(vectorizer, "/content/drive/MyDrive/smart-support-assistant/tfidf_vectorizer.pkl")

print("Baseline model and vectorizer saved!")